image: tmaier/docker-compose:18

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

before_script:
  - docker info
  - apk add --no-cache bash make git curl
  - curl -L -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - unzip terraform.zip -d /usr/local/bin/
  - rm terraform.zip

build:
  stage: build
  script:
    - ./bin/build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.zip
      - terraform-provider-conjur  # for next stage

test:
  stage: test
  script:
    - ./bin/test
