# all available options: https://goreleaser.com/customization/
project_name: terraform-provider-conjur

before:
  hooks: []

builds:
- binary: terraform-provider-conjur_v{{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: []

archives:
  - id: conjur-terraform-release-archive
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - description: Terraform provider for CyberArk Conjur
    homepage: https://github.com/cyberark/terraform-provider-conjur
    url_template: https://github.com/cyberark/terraform-provider-conjur/releases/download/v{{.Version}}/{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}.gz
    caveats: |
      After installation, you must symlink the provider into Terraform's plugins directory.
      Symlinking is necessary because Homebrew is sandboxed and cannot write to your home directory.

      # Make the plugins directory if not present
      mkdir -p ~/.terraform.d/plugins/

      # Remove any old unversioned plugins (if applicable)
      rm -f  ~/.terraform.d/plugins/terraform-provider-conjur

      # Symlink the provider to your home dir. If Homebrew is installing somewhere other than /usr/local/Cellar, update the path as well.
      ln -sf /usr/local/Cellar/terraform-provider-conjur/{{.Version}}/bin/terraform-provider-conjur_v{{.Version}} ~/.terraform.d/plugins/terraform-provider-conjur_v{{.Version}}
    dependencies:
      - terraform
    install: |
      bin.install "terraform-provider-conjur_{{.Version}}"
    test: |
      # Running bin directly gives error, exit code 1
      system "#{bin}/terraform-provider-conjur_{{.Version}}", "-h"  

    github:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

release:
  disable: true
