// Package api contains autogenerated interface from conjur api go client
package api

//go:generate interfacer -for github.com/cyberark/conjur-api-go/conjurapi.ClientV2 -as api.ClientV2 -o client_v2.gen.go
//go:generate goimports -w client_v2.gen.go
